"""Добавлены новые модели

Revision ID: 5976fe05b75d
Revises: d74b9c6ff2d7
Create Date: 2025-03-17 02:51:20.838036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5976fe05b75d'
down_revision: Union[str, None] = 'd74b9c6ff2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
