"""Добавлены новые модели

Revision ID: 8931ce4580c1
Revises: e3dc52119977
Create Date: 2025-03-17 02:35:14.294334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8931ce4580c1'
down_revision: Union[str, None] = 'e3dc52119977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_roles_name', table_name='roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_roles_name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
