"""Добавлены новые модели

Revision ID: d74b9c6ff2d7
Revises: e15712cdfbfb
Create Date: 2025-03-17 02:50:01.509271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74b9c6ff2d7'
down_revision: Union[str, None] = 'e15712cdfbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_admin_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['admin_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_admin_id_fkey', 'groups', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
