"""Synchronize models with database

Revision ID: e3dc52119977
Revises: 3565efaad097
Create Date: 2025-03-17 02:25:47.173640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dc52119977'
down_revision: Union[str, None] = '3565efaad097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_role_name', 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_role_name', 'roles', ['name'])
    # ### end Alembic commands ###
